-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 21:03:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ventadejuegos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventadejuegos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventadejuegos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ventadejuegos` ;

-- -----------------------------------------------------
-- Table `ventadejuegos`.`membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`membresia` (
  `idMembresia` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `descuento` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idMembresia`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `Membresia_idMembresia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `Membresia_idMembresia` (`Membresia_idMembresia` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`Membresia_idMembresia`)
    REFERENCES `ventadejuegos`.`membresia` (`idMembresia`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `Usuario_idUsuario` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `carrito_ibfk_1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `ventadejuegos`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`juego` (
  `idJuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `Categoria_idCategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idJuego`),
  INDEX `Categoria_idCategoria` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `juego_ibfk_1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `ventadejuegos`.`categoria` (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`carrito_has_juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`carrito_has_juego` (
  `Carrito_idCarrito` INT NOT NULL,
  `Juego_idJuego` INT NOT NULL,
  PRIMARY KEY (`Carrito_idCarrito`, `Juego_idJuego`),
  INDEX `Juego_idJuego` (`Juego_idJuego` ASC) VISIBLE,
  CONSTRAINT `carrito_has_juego_ibfk_1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `ventadejuegos`.`carrito` (`idCarrito`),
  CONSTRAINT `carrito_has_juego_ibfk_2`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `ventadejuegos`.`juego` (`idJuego`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadejuegos`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadejuegos`.`compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NULL DEFAULT NULL,
  `Juego_idJuego` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `Usuario_idUsuario` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `Juego_idJuego` (`Juego_idJuego` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `ventadejuegos`.`usuario` (`idUsuario`),
  CONSTRAINT `compra_ibfk_2`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `ventadejuegos`.`juego` (`idJuego`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
