usuario-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 22:00:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema VentaDeJuegos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VentaDeJuegos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VentaDeJuegos` DEFAULT CHARACTER SET utf8 ;
USE `VentaDeJuegos` ;

-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Juego` (
  `idJuego` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Precio` DECIMAL(2) NULL,
  `IdCategoria` INT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idJuego`),
  INDEX `fk_Juego_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Juego_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `VentaDeJuegos`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Carrito` (
  `idCarrito` INT NOT NULL,
  `idJuego` INT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `idJuego_idx` (`idJuego` ASC) VISIBLE,
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idJuego`
    FOREIGN KEY (`idJuego`)
    REFERENCES `VentaDeJuegos`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `VentaDeJuegos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Membresia` (
  `idMembresia` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Descuento%` INT NOT NULL,
  PRIMARY KEY (`idMembresia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Membresia_idMembresia` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Carrito_idCarrito`, `Nombre`, `Apellido`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  INDEX `fk_Usuario_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Usuario_Membresia1_idx` (`Membresia_idMembresia` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `VentaDeJuegos`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Membresia1`
    FOREIGN KEY (`Membresia_idMembresia`)
    REFERENCES `VentaDeJuegos`.`Membresia` (`idMembresia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Compra` (
  `idCompra` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Total` VARCHAR(45) NULL,
  `Carrito_idCarrito1` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Carrito1_idx` (`Carrito_idCarrito1` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito1`)
    REFERENCES `VentaDeJuegos`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VentaDeJuegos`.`Carrito_has_Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VentaDeJuegos`.`Carrito_has_Juego` (
  `Carrito_idCarrito` INT NOT NULL,
  `Juego_idJuego` INT NOT NULL,
  PRIMARY KEY (`Carrito_idCarrito`, `Juego_idJuego`),
  INDEX `fk_Carrito_has_Juego_Juego1_idx` (`Juego_idJuego` ASC) VISIBLE,
  INDEX `fk_Carrito_has_Juego_Carrito_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_has_Juego_Carrito`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `VentaDeJuegos`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_has_Juego_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `VentaDeJuegos`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
